### ISSUE TITLE
[Mail] faille de sécurité (xss)

### ISSUE THREAD

**Issue by eletrixtime** [edificeio/entcore#500]
Bonjour, jai trouvé une faille de sécurité ou peux je la signaler ?

**Comment by eletrixtime** [comment]
? zéro réponse...

**Comment by eletrixtime** [comment]
Projet mort ? très bien

**Comment by rdjedjig** [comment]
Bonjour,

Vous pouvez envoyer un message à l'adresse suivante : tech@opendigitaleducation.com.

**Comment by eletrixtime** [comment]
D'accord, j'ai envoyé le mail (désolé de l'attente, je n'avais pas vu la notification)
